import BerryEsseen.Certificate.Finite.LeafTree
/-!
# Compact Route B leaf certificate for `n = 1`

The prefix code is generated by the untrusted discovery helper and checked here from scratch.
Only its 29 leaves invoke the expensive numerical enclosure; rejected internal search boxes are
not recomputed.
-/

namespace BerryEsseen

set_option maxRecDepth 10000

def dyadicRouteBLeafCode01 : String :=
  "ZRZLLZLLRZRLLRZLRZLRZLLRLLZLRLLRZLZLRLLZLRLLZRLLRZLRLLRLL"

theorem dyadicRouteBLeafCodeCertificate_one :
    dyadicRouteBLeafCodeCertificate 1 dyadicRouteBLeafCode01 = true := by
  native_decide

end BerryEsseen
